services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        RUBY_VERSION: 3.4.7
        NODE_VERSION: 22.14.0
        PNPM_VERSION: 10.33.0
        # APP_ENV: development
    env_file:
      - rails.env.local
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
      - node_modules:/rails/node_modules
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]
    entrypoint: ["/rails/bin/docker-entrypoint"]

  db:
    image: mysql:8.4.5
    ports:
      - ${DB_PORT}:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: Asia/Tokyo
    platform: linux/amd64
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 1s
      timeout: 1s
      retries: 10
      start_period: 5s

volumes:
  mysql-data:
    driver: local
  bundle_cache:
    driver: local
  node_modules:
    driver: local
