[tools]
ruby = "3.4.7"
node = "22.22.2"
mysql = "8.0.33"
pnpm = "10.33.0"
"npm:commitlint" = "19.8.1"
"npm:lefthook" = "1.11.14"
"npm:prettier" = "3.5.3"
"pipx:mycli" = "1.64.0"

[hooks]
postinstall = "lefthook install"

[tasks]
rubocop = "docker compose exec app bundle exec rubocop"

[env]
DB_HOST = "localhost"
DB_PORT = "3306"
DB_USER = "user"
DB_PASSWORD = "password"
DB_ROOT_PASSWORD = "rootpassword"
